GET http://localhost:3001/progress/2 HTTP/1.1
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJEYW5pZWwiLCJlbWFpbCI6ImRhbmllbEBnbWFpbC5jb20iLCJwaG9uZW51bWJlciI6IjA1MDU1NTU1NTUiLCJpbWFnZUlEIjo0LCJ1cmwiOiIvaW1hZ2VzL2F2YXRhcnMvYWxpZW4ucG5nIiwiaWF0IjoxNzU4MzY3OTkzLCJleHAiOjE3NTg5NzI3OTN9.C0_Ph9pk7Zyg0n6PJnJA3_ZQaeH9FcGbhrJauZIvjNM