GET http://localhost:3001/categories/1/connect_task HTTP/1.1 
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJEYW5pZWwiLCJlbWFpbCI6ImRhbmllbEBnbWFpbC5jb20iLCJwaG9uZW51bWJlciI6IjA1MDIyMjMzNjYiLCJpbWFnZUlEIjo5LCJ1cmwiOiIvaW1hZ2VzL2F2YXRhcnMvZGlub3NhdXIucG5nIiwiaWF0IjoxNzUyMTUyODY4LCJleHAiOjE3NTI3NTc2Njh9.8KGrjOCKvCZXBI6fjDLm2cZh7idekCuowGPWwbOxC4w
