GET http://localhost:3001/categories HTTP/1.1
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJKYW5lIiwiZW1haWwiOiJqYW5lQGdtYWlsLmNvbSIsInBob25lbnVtYmVyIjoiMDUwMTIzNDU2NyIsImltYWdlSUQiOjEsInVybCI6Ii9pbWFnZXMvYXZhdGFycy9kb2cucG5nIiwiaWF0IjoxNzc4NjY1MDk1LCJleHAiOjE3NzkyNjk4OTV9.SP1ra5ZTbRavxX_3UYBlz5eeGTIgqZNJbI9z5qWRbuw