GET http://localhost:3001/words HTTP/1.1
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmllbEBnbWFpbC5jb20iLCJwaG9uZW51bWJlciI6IjA1MDIyMjMzNjYiLCJpYXQiOjE3NTAwMTAwODQsImV4cCI6MTc1MDYxNDg4NH0.LT0pt81jvC_nNZCCuuV8QHoNinvLD5GkVUcZ8n_rSCw