GET http://localhost:3001/progress/2 HTTP/1.1
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJOb3N0cm8iLCJlbWFpbCI6Im5vc3Ryb0BnbWFpbC5jb20iLCJwaG9uZW51bWJlciI6IjA1MDIyMjMzNTUiLCJpbWFnZUlEIjoxLCJ1cmwiOiIvaW1hZ2VzL2F2YXRhcnMvZG9nLnBuZyIsImlhdCI6MTc1MjA2NzkwOCwiZXhwIjoxNzUyNjcyNzA4fQ.OxpfDeViLr8HQRwwd12Z8LvSPDnG4qYrXR1RX26vcNE