GET http://localhost:3001/progress/2 HTTP/1.1
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJFbGxpIiwiZW1haWwiOiJlbGxpQGdtYWlsLmNvbSIsInBob25lbnVtYmVyIjoiMDUwMjIyMzM3NyIsImltYWdlSUQiOjcsInVybCI6Ii9pbWFnZXMvYXZhdGFycy9wYW5kYS5wbmciLCJpYXQiOjE3NTIyMzgxODYsImV4cCI6MTc1Mjg0Mjk4Nn0.BTXSFE5_12GFhJ0oxFF6t1BaDNecD3ln-9dlj-Zdogw