POST http://localhost:3001/progress/3 HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJOb3N0cm8iLCJlbWFpbCI6Im5vc3Ryb0BnbWFpbC5jb20iLCJwaG9uZW51bWJlciI6IjA1MDIyMjMzNTUiLCJpbWFnZUlEIjoxLCJ1cmwiOiIvaW1hZ2VzL2F2YXRhcnMvZG9nLnBuZyIsImlhdCI6MTc1MjA2NzkwOCwiZXhwIjoxNzUyNjcyNzA4fQ.OxpfDeViLr8HQRwwd12Z8LvSPDnG4qYrXR1RX26vcNE

{
    "userID": 3,
    "exerciseID": 1,
    "score_en": 10,
    "score_fi": 10,
    "score_ua": 10,
    "score_ru": 10
}