GET http://localhost:3001/words HTTP/1.1
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJEYW5pZWwiLCJlbWFpbCI6ImRhbmllbEBnbWFpbC5jb20iLCJwaG9uZW51bWJlciI6IjA1MDIyMjMzNjYiLCJpbWFnZUlEIjo5LCJ1cmwiOiIvaW1hZ2VzL2Rpbm9zYXVyLnBuZyIsImlhdCI6MTc1MTIyNzk2MywiZXhwIjoxNzUxODMyNzYzfQ.QLj3xRLKcUispv52MbCqvmOMYDy8bAbkll7OsXbuN5Y